// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Puzzle struct {
	ID        int64
	ArrayStr  sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	FirstName    string
	LastName     string
	CreatedAt    time.Time
}

type UserPuzzle struct {
	UserID    int64
	PuzzleID  int64
	CreatedAt time.Time
}
